#$ -S /bin/bash
#$ -q rnd.q,prod.q,test.q
#$ -cwd
#$ -p -1000
#$ -V

TABIX_DIR=$1

CORE_PATH=$2
OUT_PROJECT=$3
SM_TAG=$4

$TABIX_DIR/bgzip -c $CORE_PATH/$OUT_PROJECT/VCF/RELEASE/FILTERED_ON_BAIT/$SM_TAG"_MS_OnBait.vcf" \
>| $CORE_PATH/$OUT_PROJECT/VCF/RELEASE/FILTERED_ON_BAIT/TABIX/$SM_TAG"_MS_OnBait.vcf.gz"

$TABIX_DIR/tabix -f -p vcf $CORE_PATH/$OUT_PROJECT/VCF/RELEASE/FILTERED_ON_BAIT/TABIX/$SM_TAG"_MS_OnBait.vcf.gz"