#$ -S /bin/bash
#$ -q rnd.q,prod.q,test.q
#$ -cwd
#$ -p -50
#$ -V


CIDR_SEQSUITE_JAVA_DIR=$1
CIDR_SEQSUITE_6_1_1_DIR=$2
VERACODE_CSV=$3

CORE_PATH=$4
OUT_PROJECT=$5
SM_TAG=$6
TARGET_BED=$7

mkdir -p $CORE_PATH/$OUT_PROJECT/TEMP/$SM_TAG

cp $CORE_PATH/$OUT_PROJECT/SNV/RELEASE/FILTERED_ON_TARGET/$SM_TAG"_MS_OnTARGET_SNV.vcf" \
$CORE_PATH/$OUT_PROJECT/TEMP/$SM_TAG/$SM_TAG"_MS_OnTARGET_SNV.vcf"

$CIDR_SEQSUITE_JAVA_DIR/java -jar \
$CIDR_SEQSUITE_6_1_1_DIR/CIDRSeqSuite.jar \
-pipeline -concordance \
$CORE_PATH/$OUT_PROJECT/TEMP/$SM_TAG \
$CORE_PATH/$OUT_PROJECT/Pretesting/Final_Genotyping_Reports/ \
$CORE_PATH/$OUT_PROJECT/TEMP/$SM_TAG \
$TARGET_BED \
$VERACODE_CSV

mv $CORE_PATH/$OUT_PROJECT/TEMP/$SM_TAG/$SM_TAG"_concordance.csv" \
$CORE_PATH/$OUT_PROJECT/REPORTS/CONCORDANCE_MS/$SM_TAG"_concordance.csv"

mv $CORE_PATH/$OUT_PROJECT/TEMP/$SM_TAG/missing_data.csv \
$CORE_PATH/$OUT_PROJECT/REPORTS/CONCORDANCE_MS/$SM_TAG"_missing_data.csv"

mv $CORE_PATH/$OUT_PROJECT/TEMP/$SM_TAG/discordant_data.csv \
$CORE_PATH/$OUT_PROJECT/REPORTS/CONCORDANCE_MS/$SM_TAG"_discordant_calls.csv"
